# Generated by Django 4.1.4 on 2023-01-08 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('state', '0002_alter_state_options_alter_state_state_name'),
        ('walkie_talkie', '0001_initial'),
        ('post', '0001_initial'),
        ('organization', '0001_initial'),
        ('resposible', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id_accounting', models.AutoField(primary_key=True, serialize=False)),
                ('relevance', models.BooleanField(default=False, verbose_name='Актуальность')),
                ('document', models.CharField(max_length=380, verbose_name='Документ подтверждающий приём на себя рацию')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('comments', models.TextField(verbose_name='Комментарий')),
                ('id_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('id_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
                ('id_resposible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resposible.resposible')),
                ('id_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state.state')),
                ('id_walkie_talkie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walkie_talkie.walkietalkie')),
            ],
            options={
                'verbose_name': 'Учёт',
                'verbose_name_plural': 'Учёт',
            },
        ),
    ]
