# Generated by Django 4.1.4 on 2023-01-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting',
            name='id_accounting',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Порядковый номер учёта'),
        ),
    ]
