# Generated by Django 4.1.4 on 2023-01-04 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalkieTalkie',
            fields=[
                ('id_walkie_talkie', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=1200, verbose_name='Серийный номер')),
                ('frequency', models.CharField(max_length=500, verbose_name='Номинальнал частоты р/частоты (МГц)')),
                ('permission', models.CharField(max_length=1200, verbose_name='Разрешение')),
                ('callsing', models.CharField(max_length=500, verbose_name='Позывной')),
                ('certificate_number', models.CharField(max_length=500, verbose_name='Номер свидетельства')),
                ('date_of_received', models.DateTimeField(verbose_name='Дата выдачи')),
                ('use_of_RES', models.CharField(max_length=20, verbose_name='Использование РЭС')),
                ('id_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'verbose_name': 'Рация',
                'verbose_name_plural': 'Рации',
            },
        ),
    ]
