# Generated by Django 4.1.4 on 2023-01-09 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walkie_talkie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walkietalkie',
            old_name='id_walkie_talkie',
            new_name='id',
        ),
    ]
