# Generated by Django 4.1.4 on 2023-01-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkie_talkie', '0003_alter_walkietalkie_date_of_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walkietalkie',
            name='date_of_received',
            field=models.DateTimeField(verbose_name='Дата выдачи'),
        ),
    ]
