# Generated by Django 4.1.4 on 2023-01-10 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('walkie_talkie', '0004_alter_walkietalkie_date_of_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkietalkie',
            name='date_of_purchase',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата покупки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='walkietalkie',
            name='date_of_received',
            field=models.DateTimeField(verbose_name='Дата выдачи (ввод в эксплуатацию)'),
        ),
    ]
