# Generated by Django 4.1.4 on 2023-01-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id_post', models.AutoField(primary_key=True, serialize=False)),
                ('post_name', models.CharField(max_length=1000, verbose_name='Название поста')),
                ('address', models.CharField(max_length=2000, verbose_name='Адресс')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
