# Generated by Django 4.1.4 on 2023-01-09 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='id_post',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_name',
            new_name='name',
        ),
    ]
