# Generated by Django 4.1.4 on 2023-01-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_id_post_post_id_rename_post_name_post_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.CharField(max_length=2000, verbose_name='Адрес'),
        ),
    ]
