# Generated by Django 4.1.4 on 2022-12-22 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
    ]
