# Generated by Django 4.1.4 on 2023-01-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'Состояние', 'verbose_name_plural': 'Состояние'},
        ),
        migrations.AlterField(
            model_name='state',
            name='state_name',
            field=models.CharField(max_length=380, verbose_name='Состояние'),
        ),
    ]
