# Generated by Django 4.1.4 on 2023-01-09 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0002_alter_state_options_alter_state_state_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='id_state',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='state_name',
            new_name='name',
        ),
    ]
